# Generated by Django 3.2.17 on 2023-02-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20230204_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hosts',
            new_name='HostModel',
        ),
    ]
