# Generated by Django 3.2.17 on 2023-02-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_rename_hosts_hostmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostmodel',
            old_name='disk_capacity',
            new_name='diskCapacity',
        ),
        migrations.RenameField(
            model_name='hostmodel',
            old_name='mem_in_gb',
            new_name='memGB',
        ),
        migrations.RenameField(
            model_name='hostmodel',
            old_name='num_cpus',
            new_name='numCPU',
        ),
    ]
