apiVersion: v1
kind: Pod
metadata:
  name: hosts
  labels:
    name: {{ .Values.label }}
spec:
  containers:
  - name: hosts
    image: pramurthy/hosts:v1
    imagePullPolicy: Always
    command: [ "/bin/sh" ]
    args: [ "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000" ]
    ports:
    - name: app-port
      containerPort: {{.Values.containerport }}
