apiVersion: v1
kind: Service
metadata:
  name: hosts-svc
spec:
  type: NodePort
  selector:
    name: {{ .Values.labels }}
  ports:
  - name: app-svc-port
    protocol: TCP
    port: {{ .Values.containerport }}
    targetPort: {{ .Values.serviceport }}
