apiVersion: v1
kind: Pod
metadata:
  name: hosts
  labels:
    name: hostselect
spec:
  containers:
  - name: hosts
    image: pramurthy/hosts:v1
    ports:
    - name: app-port
      containerPort: 8000

